export const LANDING = '/'
export const SEARCH = '/buscar'
export const REGISTER = '/registro'
export const LOGIN = '/entrar'
export const UPLOAD = '/Cargar' //cargar
export const FORGOT = '/recuperar-contrasena'
export const VALIDATE = '/MailVal' //mailval
export const LIST = '/propiedades'
export const WITIHOW = '/Witideal' //witideal
export const BUYWITICOINS = '/comprar-witicoins' 
export const COMPRARPAQUETES = '/comprar-paquetes' /*Cambiar nombre de ruta a comprar paquetes */
export const WITICOINS = '/Witicoins' //witicoins
export const HOWITWORKS = '/como-funciona'
export const MYPROFILE = '/mi-perfil'
export const MYPROPERTIES = '/mis-propiedades'
export const MYFAVORITES = '/mis-favoritos'
export const MYMOVEMENTS = '/mis-destacados'